# Generated by Django 6.0.3 on 2026-04-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0)),
                ('wpm', models.PositiveIntegerField(default=300)),
                ('chunk_size', models.PositiveSmallIntegerField(default=1)),
                ('total_reading_time', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='documents.document')),
            ],
            options={
                'db_table': 'reading_sessions',
            },
        ),
    ]
