# Generated by Django 6.0.3 on 2026-04-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
