# Generated by Django 6.0.3 on 2026-04-09 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_document_file_alter_document_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reading_time', models.PositiveIntegerField(default=0)),
                ('words_read', models.PositiveIntegerField(default=0)),
                ('ending_wpm', models.PositiveIntegerField(default=0)),
                ('sessions_count', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_reading_logs',
                'indexes': [models.Index(fields=['user', 'date'], name='daily_readi_user_id_8f37de_idx'), models.Index(fields=['user', 'document', 'date'], name='daily_readi_user_id_60f41a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document', 'date'), name='one_log_per_doc_per_day')],
            },
        ),
    ]
