# Generated by Django 6.0.3 on 2026-05-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '__first__'),
        ('documents', '0003_alter_document_file_alter_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='catalog_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalog.catalogsource'),
        ),
    ]
