# Generated by Django 6.0.3 on 2026-04-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='focus_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='pivot_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
