# Generated by Django 6.0.3 on 2026-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences_focus_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='long_word_pause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='sentence_pause',
            field=models.BooleanField(default=False),
        ),
    ]
