# Generated by Django 6.0.3 on 2026-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreferences_long_word_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='tts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tts_voice',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
