# Generated by Django 6.0.3 on 2026-05-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gutenberg', 'Gutenberg')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, default='', max_length=500)),
                ('language', models.CharField(default='en', max_length=10)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('cover_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_words', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_sources',
                'indexes': [models.Index(fields=['platform', 'external_id'], name='catalog_sou_platfor_917d3e_idx'), models.Index(fields=['status'], name='catalog_sou_status_c98829_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_platform_ext_id')],
            },
        ),
        migrations.CreateModel(
            name='CatalogChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('word', models.CharField(max_length=200)),
                ('chapter_index', models.PositiveSmallIntegerField(default=0)),
                ('paragraph_index', models.PositiveIntegerField(default=0)),
                ('sentence_end', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='catalog.catalogsource')),
            ],
            options={
                'db_table': 'catalog_chunks',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['source', 'position'], name='catalog_chu_source__315fc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'position'), name='unique_catalog_position')],
            },
        ),
    ]
